### ISSUE TITLE
Doesn't work with latest versions of Chrome or Firefox

### ISSUE THREAD

**Issue by JordanMagnuson** [mildmojo/twine-gamepad#2]
Alas, this extension no longer appears to work with the latest versions of Chrome or Firefox...

**Comment by mildmojo** [comment]
Hi! Thanks for the note. I updated to the latest version of the HTML5 gamepad library (2 years old), and it seems to work better for me now. Please give it another try.

Note that this was developed for Twine v1; I haven't tested it with Twine v2. I'm not doing much Twine development these days so I'm not very actively maintaining this.

(Pull requests accepted!) :slightly_smiling_face:

**Comment by JordanMagnuson** [comment]
Wow, I didn't expect this to generate a response! Thanks for the quick fix!
